# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

site_name: FlooNoC

extra_css:
  - stylesheets/extra.css

theme:
  logo: img/floo_noc_material_logo.png
  favicon: img/floo_noc_favicon_logo.png
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - content.code.copy

repo_url: https://github.com/pulp-platform/FlooNoC
repo_name: pulp-platform/FlooNoC
site_url: https://pulp-platform.github.io/FlooNoC

plugins:
  - social:
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

nav:
- Home:
  - index.md
  - Repository Structure: repository_structure.md
  - License: license.md
  - Contributing: contributing.md
- Getting Started: getting_started.md
- Hardware IPs:
  - Overview: hw/overview.md
  - Links: hw/links.md
  - Router: hw/router.md
  - Network Interfaces: hw/chimneys.md
  - Common IPs: hw/common.md
  - Verification IPs: hw/vips.md
- FlooGen:
  - Overview: floogen/overview.md
  - Routing & Topologies: floogen/routing.md
  - Protocols: floogen/protocols.md
  - Endpoints: floogen/endpoints.md
  - Routers: floogen/routers.md
  - Connections: floogen/connections.md
  - CLI: floogen/cli.md
  - Known Issues: floogen/known_issues.md
- Changelog: changelog.md
